title: SpiderMonkey JavaScript/WebAssembly Engine
description: SpiderMonkey is Mozilla's JavaScript and WebAssembly Engine, used in Firefox, Servo and various other projects. It is written in C++ and Rust.
twitter_username: spidermonkeyjs

baseurl: "/"
url: "https://spidermonkey.dev"
permalink: /blog/:year/:month/:day/:title.html

plugins:
  - jekyll-feed
  - jekyll-octicons

header_pages:
  - blog.markdown
  - docs.markdown
  - contribute.markdown
  - etc.markdown

sass:
  style: compressed

collections:
  - home
