title: spidermonkey.dev
description: Website and team blog for the SpiderMonkey JavaScript engine.
twitter_username: spidermonkeyjs

baseurl: "/"
url: "https://spidermonkey.dev"
permalink: /blog/:year/:month/:day/:title.html

plugins:
  - jekyll-feed

header_pages:
  - index.markdown
  - blog.markdown
  - docs/index.markdown

sass:
  style: compressed
