title: spidermonkey.dev
description: Website and team blog for the SpiderMonkey JavaScript engine.
twitter_username: spidermonkeyjs

baseurl: "/"
url: "https://spidermonkey.dev"
permalink: /blog/:year/:month/:day/:title.html

plugins:
  - jekyll-feed
  - jekyll-octicons

header_pages:
  - blog.markdown
  - docs.markdown
  - contribute.markdown
  - etc.markdown

sass:
  style: compressed
